"""edit article table

Revision ID: 64f93945c28a
Revises: 77eaebfa8062
Create Date: 2018-12-25 14:06:08.724291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f93945c28a'
down_revision = '77eaebfa8062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_index',
                    sa.Column('web_id', sa.String(length=20), nullable=False),
                    sa.Column('board_id', sa.Integer(), nullable=False),
                    sa.Column('index', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
                    sa.PrimaryKeyConstraint('web_id')
                    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('post_ip',
                              existing_type=sa.VARCHAR(length=20),
                              nullable=True)
        batch_op.create_foreign_key(
            'fk_article_article_index', 'article_index', ['web_id'], ['web_id'])

    with op.batch_alter_table('article_history', schema=None) as batch_op:
        batch_op.alter_column('title',
                              existing_type=sa.VARCHAR(length=64),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_history', schema=None) as batch_op:
        batch_op.alter_column('title',
                              existing_type=sa.VARCHAR(length=64),
                              nullable=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_article_article_index', type_='foreignkey')
        batch_op.alter_column('post_ip',
                              existing_type=sa.VARCHAR(length=20),
                              nullable=False)

    op.drop_table('article_index')
    # ### end Alembic commands ###
