"""edit article history on delete actions

Revision ID: 6794412e2720
Revises: 64f93945c28a
Create Date: 2018-12-26 13:27:33.894791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6794412e2720'
down_revision = '64f93945c28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_push_article_history_id_article_history', type_='foreignkey')
        batch_op.create_foreign_key('fk_push_article_history_id_article_history', 'article_history', [
                                    'article_history_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_push_article_history_id_article_history', type_='foreignkey')
        batch_op.create_foreign_key('fk_push_article_history_id_article_history', 'article_history', [
                                    'article_history_id'], ['id'])

    # ### end Alembic commands ###
